### ISSUE TITLE
Release the checkpoint

### ISSUE THREAD

**Issue by funtion** [shamim-hussain/egt_pytorch#2]
Dear Authors,

I am impressed by your strong performance on pcqm4mv2. Considering the training cost, do you have any plan to release the checkpoints for further research use?

Best Regards

**Comment by shamim-hussain** [comment]
Yes, we plan to publicly release the weights of the trained models on the
PCQM4Mv2 dataset soon.

**Comment by shamim-hussain** [comment]
They are now available at [this link](https://zenodo.org/record/6680242). See the README.md for more info.
