### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by XiaoxiaoMa-MQ** [shamim-hussain/egt_pytorch#3]
Hi shamim,

Congratulations to your kdd 2022 paper.

I am very interested in your graph-transformer model and positional encoding of nodes. Your paper helps me a lot.

One thing I am confused with is the evaluation metric. Why don't you report the accuracy of all datasets and experiments? Have you got any comments from the reviewer for this issue?

**Comment by shamim-hussain** [comment]
Please see shamim-hussain/egt for the rest of the experiments. The missing
values for other models are due to the fact that they are not reported by
the authors.

**Comment by hussain2022a** [comment]
> مرحبا شميم
> 
> ألف مبروك ورقة kdd 2022 الخاصة بك.
> 
> أنا مهتم جدًا بنموذج محول الرسم البياني الخاص بك والتشفير الموضعي للعقد. ورقتك تساعدني كثيرا.
> 
> شيء واحد أنا في حيرة من أمري هو مقياس التقييم. لماذا لا تقوم بالإبلاغ عن دقة جميع مجموعات البيانات والتجارب؟ هل لديك أي تعليقات من المراجع لهذه المشكلة؟

**Comment by hussain2022a** [comment]
حسين المنهالي
